### ISSUE TITLE
Mention `#![no_std]` compatibility in the README/Docs

### ISSUE THREAD

**Issue by jamesmunns** [porglezomp/bitmatch#1]
Hey! Thanks for the awesome crate!

It might be good to mention that this crate works for `#![no_std]` usage as well in the README and crates.io docs, I was able to test that this works locally. If you set up CI in the future, feel free to ping me if you'd like help setting up a test to make sure it continues working.

I've also opened up a PR to the awesome-embedded-rust list to add this as a useful no-std crate: https://github.com/rust-embedded/awesome-embedded-rust/pull/243

**Comment by porglezomp** [comment]
What would you recommend as the best way to test the `#![no_std]` compatibility? I tried following someone's blog post about it but some of the options didn't work locally for me (I'm on a mac which changes linker behavior a bit I think). Furthermore I don't think `cargo-nono` works since it uses `std` at compile-time but presumably not at runtime?

**Comment by jamesmunns** [comment]
Hey! There are a couple guides on this I can find, but the most direct way IMO is to create a `#![no_std]` library crate that depends on `bitmatch`, and compile it for an embedded target, which definitely has no standard library available.

For example, your contents could look like this:

```rust
#![no_std]

use bitmatch::bitmatch;

pub fn hello_world() -> u32 {
    123
}

#[bitmatch]
pub fn swap_nibbles(n: u8) -> u8 {
    #[bitmatch]
    let "xxxx_yyyy" = n;
    bitpack!("yyyy_xxxx")
}
```

Then you could install support for a target, like this:

```bash
rustup target add thumbv7em-none-eabihf
```

And finally build the crate like this:

```
# in the new library crate
cargo build --target thumbv7em-none-eabihf
```

If it compiles successfully: You should be good to go!
